### ISSUE TITLE
Install failed in Red Hat Enterprise Linux or CentOS -wrong references to old path-

### ISSUE THREAD

**Issue by guillermo-musumeci** [LinOTP/LinOTP#185]
I have using LinOTP for a long time on Amazon Linux (Red Hat Enterprise Linux or CentOS) and noticed the change the URL of the documentation.

I installed the new package and it failed with error 404:

http://linotp.org/rpm/el7/linotp/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

This file does not exist, it should be: http://dist.linotp.org/rpm/el7/linotp/x86_64/repodata/repomd.xml

If I look to "/etc/yum.repos.d/linotp.repo" file the baseurl is pointing to the old url

$ cat linotp.repo
[linotp]
name=KeyIdentity LinOTP Packages for Enterprise Linux 7 - $basearch
baseurl=http://linotp.org/rpm/el7/linotp/x86_64
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LINOTP-7

[linotp-dependencies]
name=KeyIdentity LinOTP Packages required for Enterprise Linux 7
baseurl=http://linotp.org/rpm/el7/dependencies/x86_64
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LINOTP-7
$

I edited the file "/etc/yum.repos.d/linotp.repo" and then modified the path baseurl on the file to

baseurl=http://dist.linotp.org/rpm/el7/linotp/x86_64 

And then the installation works. 

Please update the package with the new base URL or put a mirror on the old URL. 

Thanks! Guillermo

**Comment by tiendatdtvt** [comment]
Hello Sir,

I got the same problem a few days ago and I fixed it as below:
Change the "/etc/yum.repos.d/linotp.repo" from linotp.org/... to dist.linotp.org/...
I hope this can help you.

Alex

**Comment by lukengda** [comment]
HI @guillermo-musumeci , thanks for very much for bringing this up. Everything should be solved now. Please reach back to us if something is still missing.

Have a nice day
Lukas
